//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newgen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Newgen.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackItem {
            get {
                return ResourceManager.GetString("BackItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string DevicesItem {
            get {
                return ResourceManager.GetString("DevicesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Newgen.
        /// </summary>
        public static string ExitItem {
            get {
                return ResourceManager.GetString("ExitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * This is your first time, so we&apos;ve prepared a tour for you. This&apos;ll take you to the whole map of Newgen. Click the &apos;Continue&apos; button below to start..
        /// </summary>
        public static string GuideFirst_Welcome_Msg1 {
            get {
                return ResourceManager.GetString("GuideFirst_Welcome_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product by NS. © 2014 NS. All rights reserved..
        /// </summary>
        public static string GuideFirst_Welcome_Msg2 {
            get {
                return ResourceManager.GetString("GuideFirst_Welcome_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://nsapps.net/apps/newgen.
        /// </summary>
        public static string Link_App {
            get {
                return ResourceManager.GetString("Link_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-hour time.
        /// </summary>
        public static string Options12H {
            get {
                return ResourceManager.GetString("Options12H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour time.
        /// </summary>
        public static string Options24H {
            get {
                return ResourceManager.GetString("Options24H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Newgen.
        /// </summary>
        public static string OptionsAbout {
            get {
                return ResourceManager.GetString("OptionsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string OptionsAboutTabHeader {
            get {
                return ResourceManager.GetString("OptionsAboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply.
        /// </summary>
        public static string OptionsApplyButton {
            get {
                return ResourceManager.GetString("OptionsApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color:.
        /// </summary>
        public static string OptionsBg {
            get {
                return ResourceManager.GetString("OptionsBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color transparency:.
        /// </summary>
        public static string OptionsBgAlpha {
            get {
                return ResourceManager.GetString("OptionsBgAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image:.
        /// </summary>
        public static string OptionsBgImg {
            get {
                return ResourceManager.GetString("OptionsBgImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select image.
        /// </summary>
        public static string OptionsBgImgSelect {
            get {
                return ResourceManager.GetString("OptionsBgImgSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use image in backgound.
        /// </summary>
        public static string OptionsBgImgUse {
            get {
                return ResourceManager.GetString("OptionsBgImgUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string OptionsCancelButton {
            get {
                return ResourceManager.GetString("OptionsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check for updates.
        /// </summary>
        public static string OptionsCFU {
            get {
                return ResourceManager.GetString("OptionsCFU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string OptionsChangeBg {
            get {
                return ResourceManager.GetString("OptionsChangeBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string OptionsChangeStaticAppWidgetBgColor {
            get {
                return ResourceManager.GetString("OptionsChangeStaticAppWidgetBgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed under Type 2 License of NS..
        /// </summary>
        public static string OptionsCopyright {
            get {
                return ResourceManager.GetString("OptionsCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable StartBar Clock.
        /// </summary>
        public static string OptionsDisableStartBarClock {
            get {
                return ResourceManager.GetString("OptionsDisableStartBarClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Newgen when Windows loads.
        /// </summary>
        public static string OptionsEnableAutoStart {
            get {
                return ResourceManager.GetString("OptionsEnableAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable hot keys ( global keyboard support ) (*).
        /// </summary>
        public static string OptionsEnableHK {
            get {
                return ResourceManager.GetString("OptionsEnableHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable logging of errors.
        /// </summary>
        public static string OptionsEnableLog {
            get {
                return ResourceManager.GetString("OptionsEnableLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Out Of Box Experience (*).
        /// </summary>
        public static string OptionsEnableOOBE {
            get {
                return ResourceManager.GetString("OptionsEnableOOBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Startbar always.
        /// </summary>
        public static string OptionsEnableShowStartbarA {
            get {
                return ResourceManager.GetString("OptionsEnableShowStartbarA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show taskbar ( in fullscreen mode ).
        /// </summary>
        public static string OptionsEnableShowTaskbar {
            get {
                return ResourceManager.GetString("OptionsEnableShowTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show taskbar always.
        /// </summary>
        public static string OptionsEnableShowTaskbarA {
            get {
                return ResourceManager.GetString("OptionsEnableShowTaskbarA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use thumbnails bar (*).
        /// </summary>
        public static string OptionsEnableTB {
            get {
                return ResourceManager.GetString("OptionsEnableTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable UserTile (User name and Picture) on main screen. (*).
        /// </summary>
        public static string OptionsEnableUserTile {
            get {
                return ResourceManager.GetString("OptionsEnableUserTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string OptionsGeneralTabHeader {
            get {
                return ResourceManager.GetString("OptionsGeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string OptionsItem {
            get {
                return ResourceManager.GetString("OptionsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string OptionsKeyboard {
            get {
                return ResourceManager.GetString("OptionsKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string OptionsLanguage {
            get {
                return ResourceManager.GetString("OptionsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen time (in minutes) (use blank or -1 for no screen):.
        /// </summary>
        public static string OptionsLockScreenTime {
            get {
                return ResourceManager.GetString("OptionsLockScreenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock widgets in their places, i.e. disable re-arrangment of widgets.
        /// </summary>
        public static string OptionsLockWidgets {
            get {
                return ResourceManager.GetString("OptionsLockWidgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string OptionsOkButton {
            get {
                return ResourceManager.GetString("OptionsOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oobe.
        /// </summary>
        public static string OptionsOOBETabHeader {
            get {
                return ResourceManager.GetString("OptionsOOBETabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Some Changes will be applied after restarting Newgen..
        /// </summary>
        public static string OptionsRestart {
            get {
                return ResourceManager.GetString("OptionsRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar Background color:.
        /// </summary>
        public static string OptionsStartBarBg {
            get {
                return ResourceManager.GetString("OptionsStartBarBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string OptionsStartBarBgChange {
            get {
                return ResourceManager.GetString("OptionsStartBarBgChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartBar Logo:.
        /// </summary>
        public static string OptionsStartBarLogo {
            get {
                return ResourceManager.GetString("OptionsStartBarLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string OptionsStartBarLogoChange {
            get {
                return ResourceManager.GetString("OptionsStartBarLogoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartScreen slide-show images (*):.
        /// </summary>
        public static string OptionsStartScreenSS {
            get {
                return ResourceManager.GetString("OptionsStartScreenSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable StartScreen slide-show (*).
        /// </summary>
        public static string OptionsStartScreenSSEnable {
            get {
                return ResourceManager.GetString("OptionsStartScreenSSEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select images.
        /// </summary>
        public static string OptionsStartScreenSSImgSelect {
            get {
                return ResourceManager.GetString("OptionsStartScreenSSImgSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartScreen slide-show interval (in seconds) (*):.
        /// </summary>
        public static string OptionsStartScreenSSTimeFrame {
            get {
                return ResourceManager.GetString("OptionsStartScreenSSTimeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartScreen Title:.
        /// </summary>
        public static string OptionsStartScreenTitle {
            get {
                return ResourceManager.GetString("OptionsStartScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles size (*):.
        /// </summary>
        public static string OptionsTilesSize {
            get {
                return ResourceManager.GetString("OptionsTilesSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space between tiles (*):.
        /// </summary>
        public static string OptionsTilesSpacing {
            get {
                return ResourceManager.GetString("OptionsTilesSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string OptionsTime {
            get {
                return ResourceManager.GetString("OptionsTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time format:.
        /// </summary>
        public static string OptionsTimeFormat {
            get {
                return ResourceManager.GetString("OptionsTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ui.
        /// </summary>
        public static string OptionsUITabHeader {
            get {
                return ResourceManager.GetString("OptionsUITabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update to latest version !.
        /// </summary>
        public static string OptionsULV {
            get {
                return ResourceManager.GetString("OptionsULV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :) updated.
        /// </summary>
        public static string OptionsUNA {
            get {
                return ResourceManager.GetString("OptionsUNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updates.
        /// </summary>
        public static string OptionsUpdatesTabHeader {
            get {
                return ResourceManager.GetString("OptionsUpdatesTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OptionsVersion {
            get {
                return ResourceManager.GetString("OptionsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback color for tiles background (*) (This only works when you don&apos;t set color):.
        /// </summary>
        public static string OptionsWidgetBgColor {
            get {
                return ResourceManager.GetString("OptionsWidgetBgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to widgets.
        /// </summary>
        public static string OptionsWidgetsTabHeader {
            get {
                return ResourceManager.GetString("OptionsWidgetsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newgen options.
        /// </summary>
        public static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin application / file.
        /// </summary>
        public static string PinAppItem {
            get {
                return ResourceManager.GetString("PinAppItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin folder.
        /// </summary>
        public static string PinDirItem {
            get {
                return ResourceManager.GetString("PinDirItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin website / url.
        /// </summary>
        public static string PinWebItem {
            get {
                return ResourceManager.GetString("PinWebItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshItem {
            get {
                return ResourceManager.GetString("RefreshItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin.
        /// </summary>
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Config.
        /// </summary>
        public static string SaveItem {
            get {
                return ResourceManager.GetString("SaveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save curent settings.
        /// </summary>
        public static string SaveSettingsItem {
            get {
                return ResourceManager.GetString("SaveSettingsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Files &amp; Folders.
        /// </summary>
        public static string SearchHub {
            get {
                return ResourceManager.GetString("SearchHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchItem {
            get {
                return ResourceManager.GetString("SearchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select friends that you want to pin on a start screen.
        /// </summary>
        public static string ShareHubTip {
            get {
                return ResourceManager.GetString("ShareHubTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareItem {
            get {
                return ResourceManager.GetString("ShareItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartItem {
            get {
                return ResourceManager.GetString("StartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newgen 13.
        /// </summary>
        public static string Text_App {
            get {
                return ResourceManager.GetString("Text_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply ....
        /// </summary>
        public static string Text_Apply {
            get {
                return ResourceManager.GetString("Text_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel ....
        /// </summary>
        public static string Text_Cancel {
            get {
                return ResourceManager.GetString("Text_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue ....
        /// </summary>
        public static string Text_Continue {
            get {
                return ResourceManager.GetString("Text_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newgen 13.
        /// </summary>
        public static string Text_DefaultTilesScreenTitle {
            get {
                return ResourceManager.GetString("Text_DefaultTilesScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newgen Help.
        /// </summary>
        public static string Text_Help_NH {
            get {
                return ResourceManager.GetString("Text_Help_NH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next ....
        /// </summary>
        public static string Text_Next {
            get {
                return ResourceManager.GetString("Text_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous ....
        /// </summary>
        public static string Text_Previous {
            get {
                return ResourceManager.GetString("Text_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Usage Data.
        /// </summary>
        public static string Text_Settings_ProvideUsageData {
            get {
                return ResourceManager.GetString("Text_Settings_ProvideUsageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us by providing application usage data for beter application experience and services. No private or personal data will be collected, neither will be shared..
        /// </summary>
        public static string Text_Settings_ProvideUsageDataInfo {
            get {
                return ResourceManager.GetString("Text_Settings_ProvideUsageDataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skip ....
        /// </summary>
        public static string Text_Skip {
            get {
                return ResourceManager.GetString("Text_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        public static string Text_Welcome {
            get {
                return ResourceManager.GetString("Text_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin widgets / tiles.
        /// </summary>
        public static string TilesItem {
            get {
                return ResourceManager.GetString("TilesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Lock ( Enable Dragging ).
        /// </summary>
        public static string UnLockItem {
            get {
                return ResourceManager.GetString("UnLockItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://nsapps.net/Apps/Newgen/?Action=BuyNow.
        /// </summary>
        public static string Url_BuyLicense {
            get {
                return ResourceManager.GetString("Url_BuyLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what&apos;s new?.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string WidgetsItem {
            get {
                return ResourceManager.GetString("WidgetsItem", resourceCulture);
            }
        }
    }
}
