//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newgen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Definitions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Definitions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Newgen.Resources.Definitions", typeof(Definitions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Newgen.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutTabHeader {
            get {
                return ResourceManager.GetString("AboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust app link ....
        /// </summary>
        public static string AppLinkTileOptionsHubTitle {
            get {
                return ResourceManager.GetString("AppLinkTileOptionsHubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply.
        /// </summary>
        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackItem {
            get {
                return ResourceManager.GetString("BackItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color:.
        /// </summary>
        public static string Bg {
            get {
                return ResourceManager.GetString("Bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color transparency:.
        /// </summary>
        public static string BgAlpha {
            get {
                return ResourceManager.GetString("BgAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image:.
        /// </summary>
        public static string BgImg {
            get {
                return ResourceManager.GetString("BgImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select image.
        /// </summary>
        public static string BgImgSelect {
            get {
                return ResourceManager.GetString("BgImgSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use image in backgound.
        /// </summary>
        public static string BgImgUse {
            get {
                return ResourceManager.GetString("BgImgUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check for updates.
        /// </summary>
        public static string CFU {
            get {
                return ResourceManager.GetString("CFU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string ChangeBg {
            get {
                return ResourceManager.GetString("ChangeBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string ChangeStaticAppWidgetBgColor {
            get {
                return ResourceManager.GetString("ChangeStaticAppWidgetBgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change tile color.
        /// </summary>
        public static string ChangeTileColor {
            get {
                return ResourceManager.GetString("ChangeTileColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check or click to enable/disable this feature..
        /// </summary>
        public static string CheckToEnableOrDisableThisFeature {
            get {
                return ResourceManager.GetString("CheckToEnableOrDisableThisFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed under Type 2 License of NS. ( http://NSApps.net/License ).
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string DevicesItem {
            get {
                return ResourceManager.GetString("DevicesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable StartBar Clock.
        /// </summary>
        public static string DisableStartBarClock {
            get {
                return ResourceManager.GetString("DisableStartBarClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want copy of downloaded update file, in case the update installation failed ?
        ///
        ///(Note: File will be copied to your desktop.).
        /// </summary>
        public static string DoYouWantCopyOfDownloadedUpdateFileInCaseTheUpdateInstallationFailedNoteFileWillBeCopiedToYourDesktop {
            get {
                return ResourceManager.GetString("DoYouWantCopyOfDownloadedUpdateFileInCaseTheUpdateInstallationFailedNoteFileWillB" +
                        "eCopiedToYourDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset Newgen settings (This will not remove your widgets, but a restart is required) ?.
        /// </summary>
        public static string DoYouWantToResetNewgenSettingsThisWillNotRemoveYourWidgetsButARestartIsRequired {
            get {
                return ResourceManager.GetString("DoYouWantToResetNewgenSettingsThisWillNotRemoveYourWidgetsButARestartIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Newgen when Windows loads.
        /// </summary>
        public static string EnableAutoStart {
            get {
                return ResourceManager.GetString("EnableAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable hot keys ( global keyboard support ) (*).
        /// </summary>
        public static string EnableHK {
            get {
                return ResourceManager.GetString("EnableHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable logging of errors.
        /// </summary>
        public static string EnableLog {
            get {
                return ResourceManager.GetString("EnableLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Out Of Box Experience (*).
        /// </summary>
        public static string EnableOOBE {
            get {
                return ResourceManager.GetString("EnableOOBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Startbar always.
        /// </summary>
        public static string EnableShowStartbarA {
            get {
                return ResourceManager.GetString("EnableShowStartbarA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show taskbar ( in fullscreen mode ).
        /// </summary>
        public static string EnableShowTaskbar {
            get {
                return ResourceManager.GetString("EnableShowTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show taskbar always.
        /// </summary>
        public static string EnableShowTaskbarA {
            get {
                return ResourceManager.GetString("EnableShowTaskbarA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use thumbnails bar (*).
        /// </summary>
        public static string EnableTB {
            get {
                return ResourceManager.GetString("EnableTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable UserBadgeControl (User name and Picture) on main screen. (*).
        /// </summary>
        public static string EnableUserTile {
            get {
                return ResourceManager.GetString("EnableUserTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Newgen.
        /// </summary>
        public static string ExitItem {
            get {
                return ResourceManager.GetString("ExitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string GeneralTabHeader {
            get {
                return ResourceManager.GetString("GeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * This is your first time, so we&apos;ve prepared a tour for you. This&apos;ll take you to the whole map of Newgen. Click the &apos;Continue&apos; button below to start..
        /// </summary>
        public static string GuideFirst_Welcome_Msg1 {
            get {
                return ResourceManager.GetString("GuideFirst_Welcome_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product by NS. © 2014 NS. All rights reserved..
        /// </summary>
        public static string GuideFirst_Welcome_Msg2 {
            get {
                return ResourceManager.GetString("GuideFirst_Welcome_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://NSApps.net/Apps/Newgen.
        /// </summary>
        public static string Link_App {
            get {
                return ResourceManager.GetString("Link_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen time (in minutes) (-1 to disable):.
        /// </summary>
        public static string LockScreenTime {
            get {
                return ResourceManager.GetString("LockScreenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Alt+F4 to quit this HtmlApp..
        /// </summary>
        public static string NWRunHelpContent {
            get {
                return ResourceManager.GetString("NWRunHelpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newgen HtmlApp Platform.
        /// </summary>
        public static string NWRunHelpTitle {
            get {
                return ResourceManager.GetString("NWRunHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oobe.
        /// </summary>
        public static string OOBETabHeader {
            get {
                return ResourceManager.GetString("OOBETabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string PackageDisable {
            get {
                return ResourceManager.GetString("PackageDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string PackageEnable {
            get {
                return ResourceManager.GetString("PackageEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string PackageRemove {
            get {
                return ResourceManager.GetString("PackageRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin application / file.
        /// </summary>
        public static string PinAppItem {
            get {
                return ResourceManager.GetString("PinAppItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin folder.
        /// </summary>
        public static string PinDirItem {
            get {
                return ResourceManager.GetString("PinDirItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin website / url.
        /// </summary>
        public static string PinWebItem {
            get {
                return ResourceManager.GetString("PinWebItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with user account image..
        /// </summary>
        public static string ProblemWithUserAccountImage {
            get {
                return ResourceManager.GetString("ProblemWithUserAccountImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Usage Data.
        /// </summary>
        public static string ProvideUsageData {
            get {
                return ResourceManager.GetString("ProvideUsageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us by providing application usage data for beter application experience and services. No private or personal data will be collected, neither will be shared..
        /// </summary>
        public static string ProvideUsageDataDescription {
            get {
                return ResourceManager.GetString("ProvideUsageDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshItem {
            get {
                return ResourceManager.GetString("RefreshItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin.
        /// </summary>
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset tile color (Restart needed !).
        /// </summary>
        public static string ResetTileColor {
            get {
                return ResourceManager.GetString("ResetTileColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Some Changes will be applied after restarting Newgen..
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Config.
        /// </summary>
        public static string SaveItem {
            get {
                return ResourceManager.GetString("SaveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save curent settings.
        /// </summary>
        public static string SaveSettingsItem {
            get {
                return ResourceManager.GetString("SaveSettingsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Files &amp; Folders.
        /// </summary>
        public static string SearchHub {
            get {
                return ResourceManager.GetString("SearchHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchItem {
            get {
                return ResourceManager.GetString("SearchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsHub {
            get {
                return ResourceManager.GetString("SettingsHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select friends that you want to pin on a start screen.
        /// </summary>
        public static string ShareHubTip {
            get {
                return ResourceManager.GetString("ShareHubTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareItem {
            get {
                return ResourceManager.GetString("ShareItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar Background color:.
        /// </summary>
        public static string StartBarBg {
            get {
                return ResourceManager.GetString("StartBarBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string StartBarBgChange {
            get {
                return ResourceManager.GetString("StartBarBgChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartBar Logo:.
        /// </summary>
        public static string StartBarLogo {
            get {
                return ResourceManager.GetString("StartBarLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string StartBarLogoChange {
            get {
                return ResourceManager.GetString("StartBarLogoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string StartBarSettingsItem {
            get {
                return ResourceManager.GetString("StartBarSettingsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartItem {
            get {
                return ResourceManager.GetString("StartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartScreen slide-show images (*):.
        /// </summary>
        public static string StartScreenSS {
            get {
                return ResourceManager.GetString("StartScreenSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable StartScreen slide-show (*).
        /// </summary>
        public static string StartScreenSSEnable {
            get {
                return ResourceManager.GetString("StartScreenSSEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select images.
        /// </summary>
        public static string StartScreenSSImgSelect {
            get {
                return ResourceManager.GetString("StartScreenSSImgSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartScreen slide-show interval (in seconds) (*):.
        /// </summary>
        public static string StartScreenSSTimeFrame {
            get {
                return ResourceManager.GetString("StartScreenSSTimeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartScreen Title:.
        /// </summary>
        public static string StartScreenTitle {
            get {
                return ResourceManager.GetString("StartScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string StoreHub {
            get {
                return ResourceManager.GetString("StoreHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string StoreItem {
            get {
                return ResourceManager.GetString("StoreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System integration.
        /// </summary>
        public static string SystemIntegration {
            get {
                return ResourceManager.GetString("SystemIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskBar.
        /// </summary>
        public static string TaskBar {
            get {
                return ResourceManager.GetString("TaskBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newgen BlueShift.
        /// </summary>
        public static string Text_App {
            get {
                return ResourceManager.GetString("Text_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply ....
        /// </summary>
        public static string Text_Apply {
            get {
                return ResourceManager.GetString("Text_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel ....
        /// </summary>
        public static string Text_Cancel {
            get {
                return ResourceManager.GetString("Text_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue ....
        /// </summary>
        public static string Text_Continue {
            get {
                return ResourceManager.GetString("Text_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newgen BlueShift.
        /// </summary>
        public static string Text_DefaultTilesScreenTitle {
            get {
                return ResourceManager.GetString("Text_DefaultTilesScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newgen Help.
        /// </summary>
        public static string Text_Help_NH {
            get {
                return ResourceManager.GetString("Text_Help_NH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next ....
        /// </summary>
        public static string Text_Next {
            get {
                return ResourceManager.GetString("Text_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous ....
        /// </summary>
        public static string Text_Previous {
            get {
                return ResourceManager.GetString("Text_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skip ....
        /// </summary>
        public static string Text_Skip {
            get {
                return ResourceManager.GetString("Text_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        public static string Text_Welcome {
            get {
                return ResourceManager.GetString("Text_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin.
        /// </summary>
        public static string TileContextMenuDisableItem {
            get {
                return ResourceManager.GetString("TileContextMenuDisableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove (Restart needed !).
        /// </summary>
        public static string TileContextMenuRemoveItem {
            get {
                return ResourceManager.GetString("TileContextMenuRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin widgets / tiles.
        /// </summary>
        public static string TilesItem {
            get {
                return ResourceManager.GetString("TilesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock tiles in their places, i.e. disable re-arrangment of tiles.
        /// </summary>
        public static string TilesLock {
            get {
                return ResourceManager.GetString("TilesLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles size (Restart needed !).
        /// </summary>
        public static string TilesSize {
            get {
                return ResourceManager.GetString("TilesSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space between tiles (Restart needed !).
        /// </summary>
        public static string TilesSpacing {
            get {
                return ResourceManager.GetString("TilesSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time format:.
        /// </summary>
        public static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-hour time.
        /// </summary>
        public static string TimeFormat12H {
            get {
                return ResourceManager.GetString("TimeFormat12H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour time.
        /// </summary>
        public static string TimeFormat24H {
            get {
                return ResourceManager.GetString("TimeFormat24H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ui.
        /// </summary>
        public static string UITabHeader {
            get {
                return ResourceManager.GetString("UITabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update to latest version !.
        /// </summary>
        public static string ULV {
            get {
                return ResourceManager.GetString("ULV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :) updated.
        /// </summary>
        public static string UNA {
            get {
                return ResourceManager.GetString("UNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to run NW !.
        /// </summary>
        public static string UnableToRunNW {
            get {
                return ResourceManager.GetString("UnableToRunNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Lock ( Enable Dragging ).
        /// </summary>
        public static string UnLockItem {
            get {
                return ResourceManager.GetString("UnLockItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updates.
        /// </summary>
        public static string UpdatesTabHeader {
            get {
                return ResourceManager.GetString("UpdatesTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://NSApps.net/Apps/Newgen.
        /// </summary>
        public static string Url_BuyLicense {
            get {
                return ResourceManager.GetString("Url_BuyLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what&apos;s new?.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback color for tiles background (*) (This only works when you don&apos;t set color):.
        /// </summary>
        public static string WidgetBgColor {
            get {
                return ResourceManager.GetString("WidgetBgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string WidgetsItem {
            get {
                return ResourceManager.GetString("WidgetsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to widgets.
        /// </summary>
        public static string WidgetsTabHeader {
            get {
                return ResourceManager.GetString("WidgetsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newgen options.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
